global using Application.DTOs.Roles;
global using Domain.POCOs;
global using Infrastructure.DataContexts;
global using Microsoft.AspNetCore.Hosting;
global using Microsoft.AspNetCore.Mvc.Testing;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using static Test.TestResources.Mocks.Role;
global using Utilities.Commons;
global using static Utilities.Extensions.GenericTypeExtension;
global using static Utilities.Helpers.BaseHelper;
global using static Utilities.Helpers.Seed;
global using System.Text;